### PR TITLE
Fixed for Babel 7 / RN 0.56

### LINKED ISSUE #29: Issue with latest RN 0.56-rc.3
Not entirely sure what the issue here is, but it seems in babel 7 it does not like the `export default class { ... }` syntax, as I am unable to build a production release.

In development it is working fine, but trying to build is throwing me a 
```
/Users/dan/code/app/node_modules/react-native-root-siblings/index.js: /Users/dan/code/app/node_modules/react-native-root-siblings/index.js: Exporting local "_default", which is not declared. (This is an error on an internal node. Probably an internal error.)
```

Fixed by adding any gibberish after the class keyword (`export default class Chicken { ... }`)

### PR DESCRIPTION
**Pull request by thatjuan**
This should resolve #29

### CODE REVIEW

**Comment by oblank** [comment]
please merge this pull request

**Comment by imamatory** [comment]
+1

**Comment by phips28** [comment]
merge pls

**Comment by sibelius** [comment]
@magicismight this looks good, can we merge it?

**Comment by jgcmarins** [comment]
You can also bypass this using package.json `resolutions`:
```json
"resolutions": {
    "react-native-root-siblings": "git+https://git@github.com/thatjuan/react-native-root-siblings.git#953b71e98e2891e543207e9aaa660d83ccd237a6"
  },
```

**Comment by sunnylqm** [comment]
Fixed in https://github.com/magicismight/react-native-root-siblings/commit/1f95f1552e30fc661d9bf4f8f54ae88aad6b5b21 instead. Thanks!

**Pull request closed without merging**
