### PR TITLE
EventEmitter NotFound

### PR DESCRIPTION
**Pull request by behzad888**
When packager cannot found this file, then an error occurred as https://github.com/facebook/react-native/issues/4968

### CODE REVIEW

**Comment by behzad888** [comment]
Whoops!! my bad

**Comment by mukeshkamboj** [comment]
@behzad888 what was the error?
I am facing the same error.

**Comment by behzad888** [comment]
@mukeshkamboj  Please see #12 and https://github.com/magicismight/react-native-root-toast/issues/44.

**Comment by mukeshkamboj** [comment]
Thanks for your help @behzad888 
Now I understand the root cause of this error.

**Comment by hmlamad** [comment]
@mukeshkamboj will you merge it in the coming days?

**Comment by hmlamad** [comment]
@magicismight will you merge it in the coming days?

**Pull request closed without merging**
