### PR TITLE
fix moved EventEmitter in RN-0.48.x

### PR DESCRIPTION
**Pull request by phips28**
fix issue #9

### CODE REVIEW

**Comment by hellogerard** [comment]
Can we get this merged & released?  Hate working off a fork...

**Comment by kevineaton** [comment]
I agree, I followed similar advice found in Firebase: https://github.com/facebook/react-native/issues/4968 and it works, but I don't want to have to edit my NPM node modules. Thanks for all your hard work!

**Comment by Almouro** [comment]
I suggested a PR which has no breaking changes. Instead of using the React Native event emitter, it uses a third party one with the same API.

**Comment by Kinka** [comment]
why not just use DeviceEventEmitter of 'react-native' ? It acts the same as I know.

**Comment by Almouro** [comment]
@Kinka so that there is no breaking change. A lot of tools depend on this module, and they would all need to implement the same specific breaking change (have a specific version for RN < 0.48 and another for RN >= 0.48)

**Pull request closed without merging**
