### PR TITLE
Update EmitEvent RN 0.48.x

### PR DESCRIPTION
**Pull request by nmjay**
Update EmitEvent RN 0.48.x

### CODE REVIEW

**Comment by t407289575** [comment]
nice!!!

**Comment by t407289575** [comment]
why i re-install root-siblings,there are no change anymore,
is still "'react-native/Libraries/EventEmitter/EventEmitter'",
my react-native is 0.48.3

**Comment by hanpanpan200** [comment]
Hi @magicismight 

This lib is cool, I got error when use it in RN 0.48, the when will this PR be merged?

**Comment by t407289575** [comment]
Hold merge soon!!!!

**Comment by wojiushirencai** [comment]
Come on baby! Just merge it!!!!

**Comment by samuelpismel** [comment]
Please merge it ;D

**Comment by brianarpie** [comment]
Please merge this, react-native-root-toast depends on it to work for RN 0.49

**Pull request closed without merging**
