### PR TITLE
Suggestion: Fix event emitter import without breaking changes

### LINKED ISSUE #9: Unable to resolve module 'react-native/Libraries/EventEmitter/EventEmitter rn-0.48.2
It seems that after this breaking change: https://github.com/facebook/react-native/commit/db3df3400a80353a0140442a5045eca344dfc76f the module is not working anymore.

### PR DESCRIPTION
**Pull request by Almouro**
Replace the use of the react native event emitter import by https://github.com/Olical/EventEmitter

Fixes #9 without the need to change version based on react native version.

A few libraries depend on `react-native-root-siblings`, so all of those libraries would have to implement a breaking change.
For instance, we're currently developing https://github.com/bamlab/react-native-form-idable which also uses `react-native-root-toast` and both are dependent on this package. That's why I think it would preferable to avoid a breaking change for a small thing like this.

What do you think @magicismight ?

### CODE REVIEW

**Comment by Almouro** [comment]
In the meantime, you can use `@bam.tech/react-native-root-siblings` with these exact changes :)

**Comment by kkortes** [comment]
Do you mean "/bamlab/react-native-root-siblings"? I didnt find anything on bam.tech.

The other issue, for me, is that I'm using "react-native-root-modal" with has this repo as a dependency. So even if I were to use your fixed one, npm install will run through the dependency installs for root-modal and screw everything up again.

I reverted my react-native version and will stick to the older one for a while, might update it later.

**Comment by Almouro** [comment]
@kkortes Sorry if that wasn't clear!

It is the github repo bamlab/react-native-root-siblings, but I published it under our npm organization @bam.tech
Meaning you can do `npm install --save @bam.tech/react-native-root-siblings` :)

**Comment by bhatti-waqas** [comment]
@Almouro : By Running npm install at some point again won't make the things back to it was before ??

**Comment by Almouro** [comment]
@bhatti-waqas it wouldn't, since it would be saved in your `package.json`

But maybe you mean if you use another package like `react-native-root-toast`? In that case, I had also published `@bam.tech/react-native-root-toast` which uses `@bam.tech/react-native-root-siblings`

**Pull request merged**
